### ISSUE TITLE
[Feature Request]: add an option to reprogram EEPROM without Installing any MBR

### ISSUE THREAD

**Issue by israpps** [parrado/softdev2-launcher#1]
this feature should come in handy for those who posses several PS2 FAT units, and want's to be capable of launching homebrew from the HDD without installing softdev2 or FreeHdBoot on all of them

**Comment by parrado** [comment]
Please describe a use case and what exactly you mean with EEPROM reprogramming, which memory address or feature do you refer to?

**Comment by israpps** [comment]
Enable HDD startup

**Comment by israpps** [comment]
For those who posses several PS2 FAT and only one HDD

**Comment by parrado** [comment]
Seems quite reasonable, I'll add the feature.

**Comment by parrado** [comment]
Solved in last commit.
