### ISSUE TITLE
SoftDev2 MBR.XIN Installation with hdl_dump

### ISSUE THREAD

**Issue by YAGAMI55** [parrado/softdev2-launcher#2]
Hello, I would like to know if it is possible to import your MBR.XIN to hard drive without using an installer, but using hdl_dump and its "initialize" command, which injects MBR.KELF

**Comment by bignaux** [comment]
That's the main reason i wrote this command :P

**Comment by parrado** [comment]
> Hello, I would like to know if it is possible to import your MBR.XIN to hard drive without using an installer, but using hdl_dump and its "initialize" command, which injects MBR.KELF

Did you manage to inject SoftDev2's MBR.XIN through hdl-dump?

**Comment by YAGAMI55** [comment]
> > Hello, I would like to know if it is possible to import your MBR.XIN to hard drive without using an installer, but using hdl_dump and its "initialize" command, which injects MBR.KELF
> 
> Did you manage to inject SoftDev2's MBR.XIN through hdl-dump?

Not yet) I not try. I read you docs and readme but i cant understand what offset your MBR.XIN use.

this for BB Navigator - MBR.KELF injection address - 0x00404000
in you source i found this:
//Sector to write
		sector = statFile.private_5 + 0x2000;

**Comment by parrado** [comment]
> > > Hello, I would like to know if it is possible to import your MBR.XIN to hard drive without using an installer, but using hdl_dump and its "initialize" command, which injects MBR.KELF
> > 
> > 
> > Did you manage to inject SoftDev2's MBR.XIN through hdl-dump?
> 
> Not yet) I not try. I read you docs and readme but i cant understand what offset your MBR.XIN use.
> 
> this for BB Navigator - MBR.KELF injection address - 0x00404000 in you source i found this: //Sector to write sector = statFile.private_5 + 0x2000;

MBR program is stored 8192 sectors after partition beginning. Then, injection address is 512x8192=4194304 or equivalently 0x400000

Please read this for further information https://www.psx-place.com/threads/official-update-lookups-and-paths.26820/#post-213183

**Comment by YAGAMI55** [comment]
> 

Ohhh. Thx) I will try soon and report back)

**Comment by YAGAMI55** [comment]
> > > > Hello, I would like to know if it is possible to import your MBR.XIN to hard drive without using an installer, but using hdl_dump and its "initialize" command, which injects MBR.KELF
> > > 
> > > 
> > > Did you manage to inject SoftDev2's MBR.XIN through hdl-dump?
> > 
> > 
> > Not yet) I not try. I read you docs and readme but i cant understand what offset your MBR.XIN use.
> > this for BB Navigator - MBR.KELF injection address - 0x00404000 in you source i found this: //Sector to write sector = statFile.private_5 + 0x2000;
> 
> MBR program is stored 8192 sectors after partition beginning. Then, injection address is 512x8192=4194304 or equivalently 0x400000
> 
> Please read this for further information https://www.psx-place.com/threads/official-update-lookups-and-paths.26820/#post-213183

Sorry for the long report
Yes. It works like a charm) Thanks for you help and softdev2)
